### ISSUE TITLE
親 有個react-native 相關的問題咨詢你 能留個聯係方式嗎

### ISSUE THREAD

**Issue by Yunnathai** [zjkhiyori/self-blog#4]
親 有個react-native 相關的問題咨詢你 能留個聯係方式嗎

在csdn 跟知乎有看到過你的文章
https://zhuanlan.zhihu.com/p/84862926

**Comment by zjkhiyori** [comment]
可以的，我的wechat: zjkhiyori

**Comment by zjkhiyori** [comment]
可以的，可以加我wechat: zjkhiyori

jamninetyfive ***@***.***> 于 2022年8月15日周一 00:57写道：
